### ISSUE TITLE
Баг в методе /online при передаче аргументов online и nickname

### ISSUE THREAD

**Issue by leonardomoorecorn** [bikinibottomcitizen/vprikol-api-python#2]
Выдает неизвестную ошибку в коде ниже:
```  
response = await client.get_player_online(server, nickname)
await message.reply(response)
```
Исправилась после замены server и nickname местами. Ошибка выглядит подобным способом:
return Response(error=response_json, success=False)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.init
pydantic.error_wrappers.ValidationError: 4 validation errors for Response
error -> error_code
  field required (type=value_error.missing)
error -> detail
  str type expected (type=type_error.str)
error -> detail
  value is not a valid dict (type=type_error.dict)
error -> detail
  str type expected (type=type_error.str)

**Comment by evans-dev1** [comment]
Исправлено в последней версии.
